name: Global Variables
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*
      - feat/**
jobs:
  output:
    environment: TEST
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependendies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
     

